feature/games
kauelima21/series-flix pull request #7
Opened 2022-10-28 17:53 UTC by eduardoxns

2022-10-28 17:57 UTC, kauelima21 approved these changes
LGTM!

2022-10-28 18:48 UTC, ayrtonmarinho approved these changes

2022-10-28 20:02 UTC, kauelima21 requested changes
No python a convenção eh usar "_":
game_name

2022-10-31 11:43 UTC, kauelima21 approved these changes
brabo D+

2022-10-31 11:51 UTC, merged